import { Equipment, Program, Trainer, MembershipPlan, Testimonial } from "./types";

export const EQUIPMENTS: Equipment[] = [
  {
    id: "cardio-1",
    name: "Commercial-Grade Treadmill",
    category: "Cardio",
    description: "Multi-layered shock absorption deck with auto-incline, 22-inch 4K coaching terminal, and 24 km/h max speed configuration.",
    specs: "3.5 HP Continuous AC Motor \u2022 150kg User Capacity",
    imageUrl: "https://images.unsplash.com/photo-1571008887538-b36bb32f4571?q=80&w=600&auto=format&fit=crop",
    stats: { label: "Top Speed", value: "24 km/h" },
  },
  {
    id: "strength-1",
    name: "ISO-Lateral Chest Press",
    category: "Strength",
    description: "Converging and diverging path of motion mimicking natural chest press feel with adjustable gas-assisted seating.",
    specs: "Independent Arms \u2022 Double Baked Powder Coating",
    imageUrl: "https://images.unsplash.com/photo-1534438327276-14e5300c3a48?q=80&w=600&auto=format&fit=crop",
    stats: { label: "Max Load", value: "220 kg" },
  },
  {
    id: "strength-2",
    name: "Premium Smith Machine",
    category: "Strength",
    description: "7-degree bar angle matching the body's natural path of squatting and pressing. Safety stops fully adjustable.",
    specs: "Linear Bearing Rails \u2022 Counterbalanced Bar",
    imageUrl: "https://images.unsplash.com/photo-1593079831268-3381b0db4a77?q=80&w=600&auto=format&fit=crop",
    stats: { label: "Safety Stops", value: "14 Levels" },
  },
  {
    id: "weights-1",
    name: "Pro-Series Dumbbell Set",
    category: "Free Weights",
    description: "Premium rubber-encased hexagonal iron dumbbells with contour knurled chrome grip profiles. Ranging from 2.5kg up to 50kg.",
    specs: "Solid Cast Iron Core \u2022 Triple Chrome Plated",
    imageUrl: "https://images.unsplash.com/photo-1638536532686-d610adfc8e5c?q=80&w=600&auto=format&fit=crop",
    stats: { label: "Step Range", value: "2.5kg - 50kg" },
  },
  {
    id: "func-1",
    name: "Battling Ropes Station",
    category: "Functional Training",
    description: "Thick core nylon weave battling ropes with customized double heat-shrink grip handles. Anchored securely for intense metabolic burn.",
    specs: "100% Poly Dacron \u2022 50 Feet Length",
    imageUrl: "https://images.unsplash.com/photo-1605296867304-46d5465a25f1?q=80&w=600&auto=format&fit=crop",
    stats: { label: "Diameter", value: "1.5 in" },
  },
  {
    id: "func-2",
    name: "Competition Kettlebells",
    category: "Functional Training",
    description: "Standard dynamic competition kettlebell modules designed with wide sandblasted steel handles for smoother high-repetition swings.",
    specs: "Single-Piece Cast Steel \u2022 Uniform Dimensions",
    imageUrl: "https://images.unsplash.com/photo-1583454124471-9f939e943265?q=80&w=600&auto=format&fit=crop",
    stats: { label: "Material", value: "Steel Alloy" },
  },
  {
    id: "strength-3",
    name: "Heavy Lat Pulldown",
    category: "Strength",
    description: "High-grade cable pulley system with premium foam thigh rollers, solid steel guide rods, and an direct load transmission pulley ratio.",
    specs: "Dual-Grip Lat Bar \u2022 120kg Precision Weight Stack",
    imageUrl: "https://images.unsplash.com/photo-1526506118085-60ce8714f8c5?q=80&w=600&auto=format&fit=crop",
    stats: { label: "Weight Stack", value: "120 kg" },
  },
  {
    id: "strength-4",
    name: "Overhead Shoulder Press",
    category: "Strength",
    description: "Counterbalanced pressing arm assembly with dual hand grip patterns. Protects shoulders while delivering concentrated mechanical load.",
    specs: "Converging Axis \u2022 4-Position Gas-Assisted Seat",
    imageUrl: "https://images.unsplash.com/photo-1581009146145-b5ef050c2e1e?q=80&w=600&auto=format&fit=crop",
    stats: { label: "Angle Adjust", value: "4 Positions" },
  },
  {
    id: "weights-2",
    name: "Barbells & Plates Station",
    category: "Free Weights",
    description: "Competition-grade Olympic straight and curl bars, coupled with high-density polyurethane color-coded bumper plates.",
    specs: "Spring Steel Olympic Bar (20kg) \u2022 Calibrated Plates",
    imageUrl: "https://images.unsplash.com/photo-1541534741688-6078c6bfb5c5?q=80&w=600&auto=format&fit=crop",
    stats: { label: "Bar Capacity", value: "450 kg" },
  },
  {
    id: "func-3",
    name: "Dual Pulley Functional Trainer",
    category: "Functional Training",
    description: "The ultimate commercial workstation with 20 adjustable pulley height ratios. Delivers unlimited resistance patterns and planes of motion.",
    specs: "2 x 90kg Independant Stacks \u2022 2:1 Effort Pulley Ratio",
    imageUrl: "https://images.unsplash.com/photo-1517838277536-f5f99be501cd?q=80&w=600&auto=format&fit=crop",
    stats: { label: "Pulley Ratio", value: "2:1 Effort" },
  },
];

export const PROGRAMS: Program[] = [
  {
    id: "prog-1",
    title: "Weight Loss & Shred",
    description: "Optimized fat oxidation programs centered around heart-rate zone tracking, high metabolic output, and active recovery.",
    duration: "12 Weeks",
    intensity: "High",
    benefits: ["Stubborn Fat Burn", "Aerobic Core Development", "High Epoc Burnout"],
  },
  {
    id: "prog-2",
    title: "Elite Muscle Building",
    description: "Hypertrophy focus utilising mechanical tension, muscle damage, and metabolic stress protocols directed by volume metrics.",
    duration: "16 Weeks",
    intensity: "Extreme",
    benefits: ["Myofibrillar Growth", "Progressive Max Overload", "Structural Strength"],
  },
  {
    id: "prog-3",
    title: "Guru Personal Training",
    description: "1-on-1 premium attention tailored explicitly around your mobility, posture corrections, biomechanics, and personalized meal plans.",
    duration: "Flexible",
    intensity: "Medium",
    benefits: ["Custom Biofeedback", "Injury Risk Prevention", "Accelerated Results"],
  },
  {
    id: "prog-4",
    title: "Metabolic CrossFit",
    description: "Unparalleled highintensity multi-articular workouts designed to build bulletproof dynamic power, endurance and agility.",
    duration: "Ongoing",
    intensity: "Extreme",
    benefits: ["Olympic Lifting Power", "Gymnastic Movement Core", "Cardiovascular Capacity"],
  },
  {
    id: "prog-5",
    title: "HIIT Explosion",
    description: "Short, aggressive blocks of work pushing anaerobic capacity to the absolute maximum to unlock insane daily calorie burn.",
    duration: "8 Weeks",
    intensity: "High",
    benefits: ["Enhanced VO2 Max", "Efficient Time Leverage", "Metabolism Boosting"],
  },
  {
    id: "prog-6",
    title: "Yoga & Zumba Flow",
    description: "Elegant mind-body flexibility, stress reduction alignment paired with high energy dance workouts to boost core endorphins.",
    duration: "Continuous",
    intensity: "Medium",
    benefits: ["Joint Decompression", "Coordination & Stamina", "Deep Stress Relief"],
  },
];

export const TRAINERS: Trainer[] = [
  {
    id: "trainer-1",
    name: "Arjun Kumar",
    role: "Head coach, Strength & Muscle",
    experience: "7+ Years",
    bio: "Former state powerlifting champion, specializing in progressive overload, biomechanics, and hardcore bodybuilding hypertrophy transformation.",
    specialties: ["Powerlifting Prep", "Myofibrillar Hypertrophy", "Injury Safe Lifting"],
    certifications: ["K11 Master Trainer Certification", "ISSA Strength Coach License"],
    imageUrl: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?q=80&w=600&auto=format&fit=crop",
  },
  {
    id: "trainer-2",
    name: "Rahul Sharma",
    role: "Head of Cardio & HIIT",
    experience: "5+ Years",
    bio: "Metabolic conditioning specialist. राहुल's ultimate calorie-burning structures are engineered to melt fat while reinforcing athletic capacity.",
    specialties: ["High Intensity HIIT", "Core Strength", "Sports Conditioning"],
    certifications: ["ACE Personal Trainer Certified", "IKFF Kettlebell Instructor"],
    imageUrl: "https://images.unsplash.com/photo-1568602471122-7832951cc4c5?q=80&w=600&auto=format&fit=crop",
  },
  {
    id: "trainer-3",
    name: "Priya Menon",
    role: "Guru Yoga & Functional",
    experience: "6+ Years",
    bio: "Passionate about structural mobility, active recovery, and mindfulness. Priya guides members toward unified muscle balance and peace.",
    specialties: ["Asana Hatha Yoga", "Functional Mobility", "Posture Rehabilitation"],
    certifications: ["RYT 500 Certified Yoga Teacher", "TRX Suspension Coach"],
    imageUrl: "https://images.unsplash.com/photo-1548690312-e3b507d8c110?q=80&w=600&auto=format&fit=crop",
  },
];

export const PLANS: MembershipPlan[] = [
  {
    id: "plan-basic",
    name: "Basic Tier",
    monthlyPrice: 1499,
    yearlyPrice: 14999,
    features: [
      "Access to cardio and strength zones",
      "Standard equipment induction",
      "Locker room & steam access",
      "Mobile App check-in",
      "1 Complementary dietitian review",
    ],
    tag: "Essential Core Access",
  },
  {
    id: "plan-standard",
    name: "Standard Tier",
    monthlyPrice: 2499,
    yearlyPrice: 24999,
    features: [
      "All Basic tier permissions",
      "Access to CrossFit & Functional zones",
      "Weekly group HIIT and Yoga workshops",
      "Custom workout tracker templates",
      "3 Personal training trial sessions",
      "Body composition diagnostics",
    ],
    tag: "The Smart Choice",
    popular: false,
  },
  {
    id: "plan-premium",
    name: "Premium Tier",
    monthlyPrice: 3999,
    yearlyPrice: 39999,
    features: [
      "All Standard tier permissions",
      "Unlimited CrossFit, Yoga & Zumba classes",
      "Dedicated 1-on-1 personal trainer",
      "Weekly bio-signature & meal protocol adjustments",
      "Priority equipment booking slots",
      "Complimentary recovery whey shakes",
      "Guest pass allowed monthly",
    ],
    tag: "Most Popular Option",
    popular: true,
  },
];

export const TESTIMONIALS: Testimonial[] = [
  {
    id: "test-1",
    name: "Ramesh Radhakrishnan",
    role: "Sales Executive",
    achievement: "Lost 12kg in 4 months!",
    comment: "The environment at Elite Fitness Salem is absolutely electrifying, motivating me to push further every single day. The trainers tailored my calorie-deficit routine perfectly.",
    rating: 5,
    imageUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?q=80&w=300&auto=format&fit=crop",
  },
  {
    id: "test-2",
    name: "Anitha Venkatesh",
    role: "Software Architect",
    achievement: "Corrected 5 years of postural back pain",
    comment: "Highly sophisticated, clean, and top-tier customer service. Priya's rehabilitation and mobility training relieved chronic posture issues from remote coding work completely.",
    rating: 5,
    imageUrl: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?q=80&w=300&auto=format&fit=crop",
  },
  {
    id: "test-3",
    name: "Karthik Raja",
    role: "Entrepreneur",
    achievement: "Gained 6kg lean muscle mass",
    comment: "Undeniably the best premium gym in Salem. Authentic, industrial-strength equipment. Arjun Kumar runs hyper-focused, result-oriented sessions. Fully worth the investment.",
    rating: 5,
    imageUrl: "https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?q=80&w=300&auto=format&fit=crop",
  },
];
